export const USER_TYPE = {
  ADMIN: 'ADMIN',
  INGENER: 'INGENER',
  RESTAURANT: 'RESTAURANT',
};

export const USER_TYPES = [
  { id: USER_TYPE.ADMIN, name: USER_TYPE.ADMIN },
  { id: USER_TYPE.INGENER, name: USER_TYPE.INGENER },
  { id: USER_TYPE.RESTAURANT, name: USER_TYPE.RESTAURANT },
];

export const RESTOURANT_TYPE = {
  MCDONALDS: 'MCDONALDS',
  KFC: 'KFC',
  HESBURGER: 'HESBURGER',
  SLOUFUDS: 'SLOUFUDS',
  CINNABONE: 'CINNABONE',
  OTHER: 'OTHER',
};

export const RESTOURANT_TYPES = [
  { id: RESTOURANT_TYPE.MACDONALDS, name: RESTOURANT_TYPE.MACDONALDS },
  { id: RESTOURANT_TYPE.KFC, name: RESTOURANT_TYPE.KFC },
  { id: RESTOURANT_TYPE.HESBURGER, name: RESTOURANT_TYPE.HESBURGER },
  { id: RESTOURANT_TYPE.SLOUFUDS, name: RESTOURANT_TYPE.SLOUFUDS },
  { id: RESTOURANT_TYPE.CINNABONE, name: RESTOURANT_TYPE.CINNABONE },
  { id: RESTOURANT_TYPE.OTHER, name: RESTOURANT_TYPE.OTHER },
];

export const VISIT_TYPE = {
  SERVICE: 'SERVICE',
  NEW_RESTOURANT: 'NEW_RESTOURANT',
  REQUEST_VISIT: 'REQUEST_VISIT',
};

export const VISIT_TYPES = [
  { id: VISIT_TYPE.SERVICE, name: VISIT_TYPE.SERVICE },
  { id: VISIT_TYPE.NEW_RESTOURANT, name: VISIT_TYPE.NEW_RESTOURANT },
  { id: VISIT_TYPE.REQUEST_VISIT, name: VISIT_TYPE.REQUEST_VISIT },
];
