export const USER_TYPE = {
  ADMIN: 'ADMIN',
  USER: 'USER',
};

export const USER_TYPES = [
  { id: USER_TYPE.ADMIN, name: USER_TYPE.ADMIN },
  { id: USER_TYPE.USER, name: USER_TYPE.USER },
];

export const RESTOURANT_TYPE = {
  MACDONALDS: 'MACDONALDS',
  KFC: 'KFC',
  HASBURGER: 'HASBURGER',
  PUZATA_HATA: 'PUZATA_HATA',
  SUSHI_MASTER: 'SUSHI_MASTER',
  OTHER: 'OTHER',
};

export const RESTOURANT_TYPES = [
  { id: RESTOURANT_TYPE.MACDONALDS, name: RESTOURANT_TYPE.MACDONALDS },
  { id: RESTOURANT_TYPE.KFC, name: RESTOURANT_TYPE.KFC },
  { id: RESTOURANT_TYPE.HASBURGER, name: RESTOURANT_TYPE.HASBURGER },
  { id: RESTOURANT_TYPE.PUZATA_HATA, name: RESTOURANT_TYPE.PUZATA_HATA },
  { id: RESTOURANT_TYPE.SUSHI_MASTER, name: RESTOURANT_TYPE.SUSHI_MASTER },
  { id: RESTOURANT_TYPE.OTHER, name: RESTOURANT_TYPE.OTHER },
];
